# texts.py

TRANS = {
    'en': {
        'welcome': "Welcome to the DV-2027 Assistant! 🇺🇸\nPlease choose your language:",
        'lang_set': "Language set to English.",
        'main_menu': "What would you like to do?",
        'btn_start': "📝 Start Application",
        'btn_price': "💰 Pricing & Info",
        'btn_help': "❓ Ask AI Helper",
        'price_info': "The service fee is 300 ETB.\nIncludes $1 fee + Professional Review.",
        'ask_firstname': "1. Please enter your **First Name** (Given Name):",
        'ask_lastname': "2. Please enter your **Grandfather's Name** (Last Name):",
        'ask_gender': "3. What is your gender?",
        'male': "Male",
        'female': "Female",
        'ask_marital': "4. What is your marital status?",
        'single': "Unmarried",
        'married': "Married",
        'divorced': "Divorced",
        'widowed': "Widowed",
        # --- NEW FAMILY TEXTS ---
        'ask_spouse_name': "💍 **Spouse Details**\nPlease enter your **Spouse's Full Name**:",
        'ask_spouse_gender': "What is your Spouse's gender?",
        'ask_spouse_photo': "📸 Upload **Spouse's Photo** (White background):",
        'ask_has_children': "5. Do you have any children (Under 21)?",
        'yes': "Yes",
        'no': "No",
        'ask_child_count': "How many children?",
        'ask_child_name': "👶 **Child {n} Details**\nEnter Full Name for Child {n}:",
        'ask_child_gender': "What is Child {n}'s gender?",
        'ask_child_photo': "📸 Upload Photo for Child {n}:",
        # ------------------------
        'ask_main_photo': "6. Finally, Upload **YOUR Photo** (Main Applicant):",
        'review_title': "📊 **Review Your Data**",
        'btn_confirm': "✅ Information Correct - Pay Now",
        'btn_edit': "❌ Start Over",
        'payment_msg': "🛡️ **Payment & Guarantee**\n\nTotal Fee: **300 ETB**.\n\n🏦 CBE: 1000583686111\n📱 Telebirr: 0996246990\n\nPlease send the screenshot here:",
        'wait_approval': "⏳ **Received!** We are verifying your payment...",
        'approved': "✅ **APPROVED!**\n\nThank you! We have received your payment and your data."
    },
    'am': {
        'welcome': "እንኳን ወደ DV-2027 ረዳት ቦት በሰላም መጡ! 🇺🇸\nእባክዎ ቋንቋ ይምረጡ፡",
        'lang_set': "ቋንቋው ወደ አማርኛ ተቀይሯል።",
        'main_menu': "ምን ማድረግ ይፈልጋሉ?",
        'btn_start': "📝 መመዝገብ ለመጀመር",
        'btn_price': "💰 ዋጋ እና መረጃ",
        'btn_help': "❓ AI መጠየቅ (Help)",
        'price_info': "የአገልግሎት ክፍያ 300 ብር ነው።\n(የ $1 ዶላር ክፍያውን እና የባለሙያ ድጋፍን ያካትታል)",
        'ask_firstname': "1. እባክዎ **የመጀመሪያ ስምዎን** ያስገቡ (First Name):",
        'ask_lastname': "2. እባክዎ **የአያትዎን ስም** ያስገቡ (Grandfather/Last Name):",
        'ask_gender': "3. ጾታዎ ምንድነው?",
        'male': "ወንድ",
        'female': "ሴት",
        'ask_marital': "4. የጋብቻ ሁኔታ?",
        'single': "ያላገባ/ች",
        'married': "ያገባ/ች",
        'divorced': "የተፋታ/ች",
        'widowed': "የሞተበት/ባት",
        # --- NEW FAMILY TEXTS ---
        'ask_spouse_name': "💍 **የባለቤትዎ መረጃ**\nእባክዎ የባለቤትዎን **ሙሉ ስም** ያስገቡ:",
        'ask_spouse_gender': "የባለቤትዎ ጾታ ምንድነው?",
        'ask_spouse_photo': "📸 የባለቤትዎን **ፎቶ** ይላኩ (ነጭ መደብ/Background):",
        'ask_has_children': "5. ልጆች አሉዎት (ከ 21 ዓመት በታች)?",
        'yes': "አዎ",
        'no': "የለኝም",
        'ask_child_count': "ስንት ልጆች አሉዎት?",
        'ask_child_name': "👶 **የልጅ {n} መረጃ**\nየልጅ {n} ሙሉ ስም ያስገቡ:",
        'ask_child_gender': "የልጅ {n} ጾታ ምንድነው?",
        'ask_child_photo': "📸 የልጅ {n} ፎቶ ይላኩ:",
        # ------------------------
        'ask_main_photo': "6. በመጨረሻም፣ **የራስዎን ፎቶ** ይላኩ (Main Applicant):",
        'review_title': "📊 **መረጃዎን ያረጋግጡ**",
        'btn_confirm': "✅ ትክክል ነው - ለመክፈል",
        'btn_edit': "❌ እንደገና ለመጀመር",
        'payment_msg': "🛡️ **ክፍያ እና ዋስትና**\n\nጠቅላላ ክፍያ: **300 ብር**.\n\n🏦 CBE: 1000583686111\n📱 Telebirr: 0996246990\n\nእባክዎ የከፈሉበትን ስክሪንሹት ይላኩ:",
        'wait_approval': "⏳ **ተቀብለናል!** ክፍያዎን እያረጋገጥን ነው ይጠብቁ...",
        'approved': "✅ **ተረጋግጧል!**\n\nእናመሰግናለን! ክፍያዎ እና መረጃዎ ደርሶናል።"
    }
}